analyzers:
- name: metrics_analyzer
data:
  datasets:
  - enabled: true
    name: Mengjiang
    path: data/xunjiang_Mengjiang.csv
    processors: 
    - name: minimax
      params: {}
    target_column: runoffs
    test_size: 0.2
    window: 15
forecast_horizon: 1
output:
  analysis_result_path: res/analysis/
  data_result_path: res/data/
models:
  full_flow_ltc_time_series_model:
    enabled: true
    params:
      forecast_steps: 1
      hidden_dim: 64
      input_dim: 10
      num_layers: 1
      output_dim: 1
      seq_length: 15
      window_size: 15
    trainer:
      batch_size: 32
      epochs: 50
      learning_rate: 0.0001
      type: BaseModelTrainer
    type: full_flow_ltc_time_series_model
  # simple_pytorch_model:
  #   enabled: false
  #   params:
  #     forecast_steps: 1
  #     input_dim: 10
  #     output_dim: 1
  #     seq_length: 15
  #   trainer:
  #     batch_size: 32
  #     epochs: 20
  #     learning_rate: 0.001
  #     type: BaseModelTrainer
  #   type: simple_pytorch_model
  # vmdi_lstm_ed_model:
  #   enabled: false
  #   params:
  #     dropout: 0.2
  #     forecast_steps: 1
  #     hidden_dim: 64
  #     input_dim: 10
  #     num_layers: 2
  #     output_dim: 1
  #     seq_length: 15
  #     target_feature_index: 3
  #   trainer:
  #     batch_size: 32
  #     epochs: 20
  #     learning_rate: 0.001
  #     type: BaseModelTrainer
  #   type: vmdi_lstm_ed_model
  # attention_gru:
  #   enabled: true
  #   params:
  #     dropout: 0.1
  #     forecast_steps: 1
  #     hidden_dim: 64
  #     input_dim: 10
  #     num_layers: 2
  #   trainer:
  #     batch_size: 32
  #     epochs: 100
  #     learning_rate: 0.001
  #     type: BaseModelTrainer
  #   type: attention_gru
  # cnn_transformer:
  #   enabled: false
  #   params:
  #     dropout: 0.1
  #     forecast_steps: 1
  #     hidden_dim: 64
  #     input_dim: 10
  #     num_heads: 4
  #     num_layers: 2
  #     seq_length: 15
  #   trainer:
  #     batch_size: 32
  #     epochs: 50
  #     learning_rate: 0.001
  #     type: BaseModelTrainer
  #   type: cnn_transformer
  # eklt_model:
  #   enabled: false
  #   params:
  #     dropout: 0.1
  #     forecast_steps: 1
  #     input_dim: 10
  #     lstm_hidden_dim: 64
  #     lstm_num_layers: 2
  #     output_dim: 1
  #     seq_length: 30
  #     transformer_d_model: 64
  #     transformer_dim_feedforward: 128
  #     transformer_nhead: 8
  #     transformer_num_layers: 2
  #   trainer:
  #     batch_size: 32
  #     epochs: 100
  #     learning_rate: 0.001
  #     type: BaseModelTrainer
  #   type: eklt_model
  # KAN:
  #   enabled: true
  #   params:
  #     feature_size: 10
  #     forecast_horizon: 1
  #     grid_eps: 0.02
  #     grid_range:
  #     - -1
  #     - 1
  #     grid_size: 5
  #     kan_layers_hidden:
  #     - 150
  #     - 64
  #     - 32
  #     - 1
  #     scale_base: 1.0
  #     scale_noise: 0.1
  #     scale_spline: 1.0
  #     seq_length: 15
  #     spline_order: 3
  #   trainer:
  #     batch_size: 32
  #     epochs: 20
  #     learning_rate: 0.001
  #     type: BaseModelTrainer
  #   type: KAN
  # grku_time_series_model:
  #   enabled: true
  #   params:
  #     grid_eps: 0.05
  #     grid_range:
  #     - -1
  #     - 1
  #     grid_size: 10
  #     hidden_dim: 128
  #     input_dim: 10
  #     num_layers: 3
  #     output_dim: 1
  #     rag_dataset_path: data/meta
  #     ragon: true
  #     scale_base: 1
  #     scale_noise: 0.2
  #     scale_spline: 1.5
  #     seq_length: 15
  #     spline_order: 3
  #     top_k: 4
  #   trainer:
  #     batch_size: 32
  #     epochs: 20
  #     learning_rate: 0.001
  #     type: BaseModelTrainer
  #   type: grku_time_series_model
  # gru_time_series_model:
  #   enabled: false
  #   params:
  #     forecast_steps: 1
  #     hidden_dim: 64
  #     input_dim: 10
  #     num_layers: 2
  #     seq_length: 15
  #   trainer:
  #     batch_size: 32
  #     epochs: 20
  #     learning_rate: 0.001
  #     type: BaseModelTrainer
  #   type: gru_time_series_model
  # lstm_time_series_model:
  #   enabled: true
  #   params:
  #     forecast_steps: 1
  #     hidden_dim: 64
  #     input_dim: 10
  #     num_layers: 2
  #     seq_length: 15
  #   trainer:
  #     batch_size: 32
  #     epochs: 20
  #     learning_rate: 0.001
  #     type: BaseModelTrainer
  #   type: lstm_time_series_model
